site_name: My FastAPI Docs
site_url: https://AryanT7.github.io/SE-Fall-25-Group-2/
docs_dir: docs
site_dir: site
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: indigo

nav:
  - Home: index.md
  - API Reference: openapi.md

plugins:
  - search
  - redoc-tag
